version: '3'
services:
  # 容器名
  apitest-db: 
      # 镜像
      image: docker.io/mysql:5.7
      container_name: apitest-db
      # 获取root权限
      privileged: true
      # 环境变量
      environment:
      - MYSQL_DATABASE=apitest
      - MYSQL_ROOT_PASSWORD=123456
      # 目录共享,格式 宿主机目录:容器目录
      volumes:
      - /Users/huangrong/workspace/autotest/mysql:/var/lib/mysql
      # 端口映射,格式 宿主机端口:容器端口
      ports:
      - 3306:3306
      # 容器开机启动命令
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --socket=/var/lib/mysql/mysql.sock

  apitest:
      build: /Users/huangrong/workspace/autotest/apitest
      image: apitest:latest
      container_name: apitest
      # 依赖
      depends_on:
      - apitest-db
      privileged: true
      # 共享目录到容器,每次启动容器会copy宿主机代码
      volumes:
      - /Users/huangrong/workspace/autotest/apitest:/opt/workspace/ApiTest
      ports:
      - 8092:8092
      command: /bin/sh start.sh

  apitest-web:
      build: /Users/huangrong/workspace/autotest/apitest-web
      image: apitest-web:latest
      container_name: apitest-web
      # 依赖
      privileged: true
      # 共享目录到容器,每次启动容器会copy宿主机代码
      volumes:
      - /Users/huangrong/workspace/autotest/apitest-web:/opt/workspace/ApiTest-Web
      ports:
      - 8090:8090
      command: /bin/sh -c '\cp -rf /opt/workspace/ApiTest-Web/default.conf /etc/nginx/conf.d/ && \cp -rf /opt/workspace/ApiTest-Web/dist/  /usr/share/nginx/html/ && nginx -g "daemon off;"'
