# Generated by Django 2.0.2 on 2019-12-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20191210_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigrouplevelfirst',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiGroupLevelFirst', verbose_name='父分组'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Group', verbose_name='父分组'),
        ),
    ]
