# Generated by Django 2.0.2 on 2019-12-18 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0004_auto_20191211_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationresult',
            name='user',
            field=models.ForeignKey(max_length=1024, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
    ]
