# Generated by Django 2.0.2 on 2019-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_publishconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='sendEmail',
            field=models.IntegerField(blank=True, choices=[('0', '不发送'), ('1', '发送'), ('2', '当成功发送'), ('3', '当失败发送')], default=0, null=True, verbose_name='发送邮件'),
        ),
        migrations.AlterField(
            model_name='publishconfig',
            name='sendEmail',
            field=models.IntegerField(blank=True, choices=[('0', '不发送'), ('1', '发送'), ('2', '当成功发送'), ('3', '当失败发送')], default=0, null=True, verbose_name='发送邮件'),
        ),
    ]
