# Generated by Django 2.0.2 on 2020-01-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_auto_20200113_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutomationCoverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('automations', models.CharField(max_length=1024, verbose_name='关联用例')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo', verbose_name='接口')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_project', to='api_test.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '接口自动化覆盖',
                'verbose_name_plural': '接口自动化覆盖管理',
            },
        ),
    ]
