# Generated by Django 2.0.2 on 2020-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_auto_20200219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationresult',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='输入'),
        ),
    ]
