# Generated by Django 2.0.2 on 2020-02-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_auto_20200219_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='businessline',
            field=models.CharField(max_length=50, null=True, verbose_name='业务线'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automationUser', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
