# Generated by Django 2.0.2 on 2020-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_auto_20200227_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigrouplevelfirst',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='自动化名称'),
        ),
        migrations.AlterField(
            model_name='automationresult',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='automationstep',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='步骤名称'),
        ),
        migrations.AlterField(
            model_name='automationtask',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='名称'),
        ),
    ]
